---
    apiVersion: v1
    kind: Namespace
    metadata: 
        name: dev
        labels:
          name: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-demo
  namespace: dev
spec:
  hard:
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: dev 
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx
