apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ricardocg94/frontend-k8s-hands:v1
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s
  labels: 
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  #Puerto del servicio
      targetPort: 80 #puerto dentro del contenedor
