apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo
    image: vish/stress
    resources:
      limits:
        cpu: "1"  # extra 
      requests:
        cpu: "0.5"  #garantizado
    args:
    - -cpus
    - "2"